name: Android CI

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Build variant'
        required: true
        default: fullRelease
        type: choice
        options: [fullRelease, aapsclientRelease, aapsclient2Release, pumpcontrolRelease]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew :app:assemble${{ github.event.inputs.variant }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.variant }}
          path: app/build/outputs/apk/**/**/*.apk
